service: auth-service

provider:
  name: aws
  runtime: nodejs22.x

functions:
  auth:
    handler: dist/main.handler
    timeout: 30
    events:
      - http:
          path: /
          method: get

plugins:
  - serverless-offline
