apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  labels:
    app: auth
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: f64franco/unimarket-auth-service:prod-latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: APP_PORT
              value: "3000"
            - name: DB_HOST
              value: "unimarket.cpamg46ggn7h.us-east-1.rds.amazonaws.com"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASS
              value: "MagIch_JEfroCHuzEBr2"
            - name: DB_DATABASE
              value: "postgres"