service: chat-service

provider:
  name: aws
  runtime: nodejs22.x
  region: us-east-1
  environment:
    DYNAMODB_TABLE: unimarket-chat-connections
    IS_OFFLINE: ${opt:stage, 'dev'}

custom:
  serverless-offline:
    httpPort: 4000
    websocketPort: 4001
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true

functions:
  websocket:
    handler: dist/src/main.handler
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
      - websocket:
          route: sendMessage

plugins:
  - serverless-dynamodb-local
  - serverless-offline

resources:
  Resources:
    ChatConnectionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: unimarket-chat-connections
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
