service: users-service

provider:
  name: aws
  runtime: nodejs22.x

functions:
  users:
    handler: dist/main.handler
    timeout: 30
    events:
      - http:
          path: /
          method: get
      - http:
          path: users
          method: post
      - http:
          path: users
          method: get
      - http:
          path: users/{userId}
          method: get
      - http:
          path: users/{userId}
          method: patch
      - http:
          path: users/{userId}
          method: delete

plugins:
  - serverless-offline
